version: "3.7"

services:

  postgres:
    container_name: 'raf-crm-postgres'
    image: 'postgres:16.3'
    restart: always
    ports:
      - '5433:5432'
    environment:
      - 'POSTGRES_USER=username'
      - 'POSTGRES_DB=main_db'
      - 'POSTGRES_PASSWORD=password'
